# Generated by Django 4.0.4 on 2023-07-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_friendrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AddField(
            model_name='chat',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
