# Generated by Django 4.0.4 on 2023-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_options_chat_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
